### ISSUE TITLE
Daemonize & Add Scheduled Tasks within withings-sync for non-k8s deployments

### ISSUE THREAD

**Issue by delize** [jaroslawhartman/withings-sync#93]
So far, I really love the tool, and am glad that I came by it, as other tools I have been using to sync data have not been functioning properly to actually transmit data from Withings into Garmin.

With that said, I am aware of the k8s cron/scheduled task functions, however, I would like to request that the docker container run off a scheduled task inherently. 

For those of us that use docker-compose, but do not use K8s, this is a better alternative compared to running `docker start withings` via cronjob. 

This would ultimately mean that the docker container becomes daemonized.

Really appreciate the tool so far!

**Comment by longstone** [comment]
I see your point. Currently I've no time to invest for this. So in the meantime I just did it with Ofelia (not happy with that approach, but it gets the job done).

  ```
ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      ofelia.job-exec.withings-sync.container: "withings-sync"
      ofelia.job-exec.withings-sync.schedule: "@every 3h"
      ofelia.job-exec.withings-sync.command: "withings-sync --gu username --gp 'password'"
    depends_on:
      - withings-sync
  withings-sync:
    container_name: withings-sync
    image: ghcr.io/jaroslawhartman/withings-sync:master
    volumes:
      - "${VOLUME_PATH}/withings-sync:/root"
    environment:
      - TZ=${TIME_ZONE}
    entrypoint: [ "/bin/sh", "-c" ,"withings-sync --gu username --gp 'password' >> /root/log.txt && tail -f /root/log.txt" ]
```
